// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: algorithm.proto

#include "algorithm.pb.h"
#include "algorithm.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace service_v2 {

static const char* Inference_method_names[] = {
  "/service_v2.Inference/Inference",
};

std::unique_ptr< Inference::Stub> Inference::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Inference::Stub> stub(new Inference::Stub(channel, options));
  return stub;
}

Inference::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Inference_(Inference_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Inference::Stub::Inference(::grpc::ClientContext* context, const ::service_v2::InferenceRequest& request, ::service_v2::InferenceReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::service_v2::InferenceRequest, ::service_v2::InferenceReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Inference_, context, request, response);
}

void Inference::Stub::async::Inference(::grpc::ClientContext* context, const ::service_v2::InferenceRequest* request, ::service_v2::InferenceReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::service_v2::InferenceRequest, ::service_v2::InferenceReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Inference_, context, request, response, std::move(f));
}

void Inference::Stub::async::Inference(::grpc::ClientContext* context, const ::service_v2::InferenceRequest* request, ::service_v2::InferenceReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Inference_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::service_v2::InferenceReply>* Inference::Stub::PrepareAsyncInferenceRaw(::grpc::ClientContext* context, const ::service_v2::InferenceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::service_v2::InferenceReply, ::service_v2::InferenceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Inference_, context, request);
}

::grpc::ClientAsyncResponseReader< ::service_v2::InferenceReply>* Inference::Stub::AsyncInferenceRaw(::grpc::ClientContext* context, const ::service_v2::InferenceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInferenceRaw(context, request, cq);
  result->StartCall();
  return result;
}

Inference::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Inference_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Inference::Service, ::service_v2::InferenceRequest, ::service_v2::InferenceReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Inference::Service* service,
             ::grpc::ServerContext* ctx,
             const ::service_v2::InferenceRequest* req,
             ::service_v2::InferenceReply* resp) {
               return service->Inference(ctx, req, resp);
             }, this)));
}

Inference::Service::~Service() {
}

::grpc::Status Inference::Service::Inference(::grpc::ServerContext* context, const ::service_v2::InferenceRequest* request, ::service_v2::InferenceReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace service_v2

